# Generated by Django 6.1.1 on 2026-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('nota', models.IntegerField()),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
